FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json turbo.json ./
COPY packages ./packages
COPY tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

FROM node:22-bookworm-slim
WORKDIR /app
ARG SERVICE=user-service
ENV SERVICE=${SERVICE}
ENV NODE_ENV=production
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
CMD node dist/services/${SERVICE}/src/index.js
